input_data = open('input.txt', 'r')
data = input_data.read()
data = data.split() 
a = int(data[0]) 
b = int(data[1]) 
output_data = open('output1.txt', 'w')
output_data.write(str(a + b)) 
output_data.close()