input_data = open('input.txt', 'r')
a = input_data.readline()
print(a)
output_data = open('output.txt', 'w')
output_data.write(str(a))
output_data.write(' ')
input_data.close()
output_data.close()